apiVersion: apps/v1
kind: Deployment
metadata:
  name: producto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producto-app
  template:
    metadata:
      labels:
        app: producto-app
    spec:
      containers:
      - name: producto-app
        image: ingrid911/producto:tag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producto-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: producto-app
